name: Publish

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: |
          8
          16
          17

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish to Modrinth
      uses: Apehum/mc-publish@v1.1
      with:
        modrinth-id: K1y8brkJ
        modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        loaders: |
          fabric
          forge
        game-versions: |
          1.17.1
          1.18.2
          1.19.2
          1.19.3
          1.19.4
          1.20.1
          1.20.3
          1.20.3
          1.20.4
          1.20.5
          1.20.6
        
    - name: Publish to GitHub
      uses: Apehum/mc-publish@v1.1
      with:
        files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: false
